**7.1 누락된 데이터 처리하기**

In [1]:
import pandas as pd
import numpy as np

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [3]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [4]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

**7.1.1 누락된 데이터 골라내기**

In [5]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [6]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [7]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])
cleaned = data.dropna()
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [8]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [9]:
data.dropna(how='all')      #모두 NA 값인 로우만 제외시킨다.

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [10]:
data[4] = NA
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [11]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [12]:
df = pd.DataFrame(np.random.randn(7,3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df

0         1         2
0 -0.280854       NaN       NaN
1  0.091367       NaN       NaN
2  1.154966       NaN  0.483834
3  0.052660       NaN  0.680898
4  0.687296 -0.281581  0.363618
5  0.772409  2.014132  0.650973
6 -0.834125 -1.583545 -0.709380

In [13]:
df.dropna()

0         1         2
4  0.687296 -0.281581  0.363618
5  0.772409  2.014132  0.650973
6 -0.834125 -1.583545 -0.709380

In [14]:
df.dropna(thresh=2)     #2개 이상의 NaN을 가진 row만 drop하라.

0         1         2
2  1.154966       NaN  0.483834
3  0.052660       NaN  0.680898
4  0.687296 -0.281581  0.363618
5  0.772409  2.014132  0.650973
6 -0.834125 -1.583545 -0.709380

**7.1.2 결측치 채우기**

In [15]:
df.fillna(0)

0         1         2
0 -0.280854  0.000000  0.000000
1  0.091367  0.000000  0.000000
2  1.154966  0.000000  0.483834
3  0.052660  0.000000  0.680898
4  0.687296 -0.281581  0.363618
5  0.772409  2.014132  0.650973
6 -0.834125 -1.583545 -0.709380

In [16]:
df.fillna({1:0.5,2:0})    #col1에는 0.5 대입, col2에는 0 대입.

0         1         2
0 -0.280854  0.500000  0.000000
1  0.091367  0.500000  0.000000
2  1.154966  0.500000  0.483834
3  0.052660  0.500000  0.680898
4  0.687296 -0.281581  0.363618
5  0.772409  2.014132  0.650973
6 -0.834125 -1.583545 -0.709380

In [17]:
_ = df.fillna(0, inplace=True)      #기존 객체를 변경
df

0         1         2
0 -0.280854  0.000000  0.000000
1  0.091367  0.000000  0.000000
2  1.154966  0.000000  0.483834
3  0.052660  0.000000  0.680898
4  0.687296 -0.281581  0.363618
5  0.772409  2.014132  0.650973
6 -0.834125 -1.583545 -0.709380

In [18]:
df = pd.DataFrame(np.random.randn(6,3))
df.iloc[2:, 1] = NA
df.iloc[4:, 2] = NA
df

0         1         2
0  1.032182 -1.685520 -0.099828
1  0.693426 -2.058778 -1.256164
2  1.202333       NaN -0.209196
3  0.530894       NaN -2.212111
4 -0.468776       NaN       NaN
5  0.450077       NaN       NaN

In [19]:
df.fillna(method='ffill')

0         1         2
0  1.032182 -1.685520 -0.099828
1  0.693426 -2.058778 -1.256164
2  1.202333 -2.058778 -0.209196
3  0.530894 -2.058778 -2.212111
4 -0.468776 -2.058778 -2.212111
5  0.450077 -2.058778 -2.212111

In [20]:
df.fillna(method='ffill', limit=2)

0         1         2
0  1.032182 -1.685520 -0.099828
1  0.693426 -2.058778 -1.256164
2  1.202333 -2.058778 -0.209196
3  0.530894 -2.058778 -2.212111
4 -0.468776       NaN -2.212111
5  0.450077       NaN -2.212111

In [21]:
data = pd.Series([1., NA, 3.5, NA, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

**7.2 데이터 변형**

**7.2.1 중복 제거하기**

In [22]:
data = pd.DataFrame({'k1':['one','two']*3 + ['two'],
                     'k2':[1,1,2,3,3,4,4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [23]:
data.duplicated()   #각 로우가 중복인지 아닌지 알려주는 bool series를 반환함.

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [24]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [25]:
data['v1'] = range(7)
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [26]:
data.drop_duplicates(['k1','k2'],keep='last')

#duplicated와 drop_duplicates는 기본적으로 처음 발견된 값을 유지한다.
#keep='last' 옵션을 넘기면 마지막으로 발견된 값을 반환한다.

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

**7.2.2 함수나 매핑을 이용해서 데이터 변형하기**

In [27]:
data = pd.DataFrame({'food':['bacon','pulled pork','bacon','Pastrami','corned beef','Bacon','pastrami','honey ham','nova lox'],
                     'ounces':[4,3,12,6,7.5,8,3,5,6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [28]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [29]:
lowercased = data['food'].str.lower()
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [30]:
data['animal'] = lowercased.map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [31]:
data['food'].map(lambda x: meat_to_animal[x.lower()])
data

#map 메서드를 사용하면 데이터의 요소별 변환 및 데이터를 다듬는 작업을 편리하게 수행할 수 있다.

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

**7.2.3 값 치환하기**

In [32]:
data = pd.Series([1.,-999.,2.,-999.,-1000.,3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [33]:
data.replace(-999,np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [34]:
data.replace([-999,-1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [35]:
data.replace([-999,-1000], [np.nan,0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [36]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

**7.2.4 축 색인 이름 바꾸기**

In [37]:
data = pd.DataFrame(np.arange(12).reshape((3,4)),
                    index=['Ohio','Colorado','New York'],
                    columns=['one','two','three','four'])

In [38]:
transform = lambda x: x[:4].upper()
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [39]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [40]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [41]:
data.rename(index={'OHIO':'INDIANA'}, columns={'three':'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [42]:
data.rename(index={'OHIO':'INDIANA'}, inplace=True)
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

**7.2.5 개별화와 양자화**

In [43]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins = [18,25,35,60,100]

cats = pd.cut(ages,bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [44]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [45]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [46]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [47]:
pd.cut(ages, [18,26,36,61,100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [48]:
group_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAge', 'MiddleAge', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAge' < 'Senior']

In [49]:
data = np.random.rand(20)
pd.cut(data,4,precision=2)

[(0.53, 0.75], (0.75, 0.98], (0.3, 0.53], (0.073, 0.3], (0.073, 0.3], ..., (0.75, 0.98], (0.3, 0.53], (0.75, 0.98], (0.073, 0.3], (0.3, 0.53]]
Length: 20
Categories (4, interval[float64]): [(0.073, 0.3] < (0.3, 0.53] < (0.53, 0.75] < (0.75, 0.98]]

In [50]:
data = np.random.randn(1000)
cats = pd.qcut(data,4)
cats

[(0.648, 3.236], (-0.684, -0.00171], (-2.989, -0.684], (-0.00171, 0.648], (-0.684, -0.00171], ..., (-0.00171, 0.648], (0.648, 3.236], (-0.684, -0.00171], (-0.684, -0.00171], (-0.00171, 0.648]]
Length: 1000
Categories (4, interval[float64]): [(-2.989, -0.684] < (-0.684, -0.00171] < (-0.00171, 0.648] <
                                    (0.648, 3.236]]

In [51]:
pd.value_counts(cats)

(0.648, 3.236]        250
(-0.00171, 0.648]     250
(-0.684, -0.00171]    250
(-2.989, -0.684]      250
dtype: int64

In [52]:
pd.qcut(data,[0,0.1,0.5,0.9,1.])

[(1.279, 3.236], (-1.215, -0.00171], (-2.989, -1.215], (-0.00171, 1.279], (-1.215, -0.00171], ..., (-0.00171, 1.279], (-0.00171, 1.279], (-1.215, -0.00171], (-1.215, -0.00171], (-0.00171, 1.279]]
Length: 1000
Categories (4, interval[float64]): [(-2.989, -1.215] < (-1.215, -0.00171] < (-0.00171, 1.279] <
                                    (1.279, 3.236]]

**7.2.6 특잇값을 찾고 제외하기**

In [53]:
data = pd.DataFrame(np.random.randn(1000,4))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.017932     0.048227     0.044048    -0.011471
std       1.028714     0.996353     0.986561     1.046595
min      -2.974885    -3.473354    -2.882014    -3.248404
25%      -0.699700    -0.637543    -0.647410    -0.730949
50%       0.010424     0.022570     0.053669     0.008501
75%       0.705384     0.739839     0.685441     0.700994
max       3.178202     3.012384     2.985528     3.331373

In [54]:
col = data[2]
col[np.abs(col)>3]

Series([], Name: 2, dtype: float64)

In [55]:
data[(np.abs(data)>3).any(1)]

0         1         2         3
57   1.074739  0.387729  0.110790 -3.061379
114 -0.148047 -0.525793  1.234000 -3.057868
160  0.238973  3.012384  1.084169  0.651865
278 -0.478124  0.396470  0.051271  3.058772
314  3.178202 -1.259272  0.573812  0.153913
441  1.282074  0.175340 -0.040759  3.331373
631 -0.425892  1.565670  0.217288 -3.248404
659 -0.040007 -1.530235  0.287964  3.038293
883  0.883388 -3.473354 -1.017377 -1.506433
982 -1.080468 -0.065160 -0.078700 -3.085604

In [56]:
data[np.abs(data)>3] = np.sign(data)*3      #np.sign(x): x가 양수이면 1을, 음수이면 -1을 반환한다.
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.017754     0.048688     0.044048    -0.011447
std       1.028181     0.994753     0.986561     1.043971
min      -2.974885    -3.000000    -2.882014    -3.000000
25%      -0.699700    -0.637543    -0.647410    -0.730949
50%       0.010424     0.022570     0.053669     0.008501
75%       0.705384     0.739839     0.685441     0.700994
max       3.000000     3.000000     2.985528     3.000000

In [57]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0 -1.0  1.0
2  1.0  1.0  1.0  1.0
3 -1.0 -1.0  1.0 -1.0
4  1.0  1.0  1.0  1.0

**7.2.7 치환과 임의 샘플링**

In [58]:
df = pd.DataFrame(np.arange(5*4).reshape((5,4)))
sampler = np.random.permutation(5)
sampler

array([4, 3, 2, 1, 0])

In [59]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [60]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
2   8   9  10  11
1   4   5   6   7
0   0   1   2   3

In [61]:
df.sample(n=3)

0  1   2   3
2  8  9  10  11
1  4  5   6   7
0  0  1   2   3

In [62]:
choices = pd.Series([5,7,-1,6,4])
draws = choices.sample(n=10, replace=True)
draws

2   -1
2   -1
4    4
2   -1
1    7
0    5
3    6
4    4
0    5
0    5
dtype: int64

**7.2.8 표시자/더미 변수 계산하기**
(복습하기.. 좀 어려움ㅠ)

In [63]:
df = pd.DataFrame({'key':['b','b','a','c','a','b'],
                   'data1':range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [64]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [65]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [66]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('https://raw.githubusercontent.com/wesm/pydata-book/2nd-edition/datasets/movielens/movies.dat',sep='::',header=None, names=mnames)

/usr/local/lib/python3.7/dist-packages/pandas/io/parsers.py:767: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return read_csv(**locals())


In [67]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [68]:
all_genres = []
for x in movies.genres:
  all_genres.extend(x.split('|'))

genres = pd.unique(all_genres)
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [69]:
zero_matrix = np.zeros((len(movies), len(genres)))
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [70]:
gen = movies.genres[0]
gen.split('|')

['Animation', "Children's", 'Comedy']

In [71]:
dummies.columns.get_indexer(gen.split('|'))     #아래의 text참고하기. (get_indexer: index값 찾기)

array([0, 1, 2])

to_match와 공통되는 unique_vals 값 인덱스값 찾기
```
to_match = pd.Series(['c','a','b','b','c','a'])
unique_vals = pd.Series(['c','b','a'])

pd.Index(unique_vals).get_indexer(to_match)
```

In [72]:
for i, gen in enumerate(movies.genres):
  indices = dummies.columns.get_indexer(gen.split('|'))
  dummies.iloc[i, indices] = 1

In [73]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Adventure                                0
Genre_Fantasy                                  0
Genre_Romance                                  0
Genre_Drama                                    0
Genre_Action                                   0
Genre_Crime                                    0
Genre_Thriller                                 0
Genre_Horror                                   0
Genre_Sci-Fi                                   0
Genre_Documentary                              0
Genre_War                                      0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Film-Noir                                0
Genre_Western       

In [74]:
np.random.seed(12345)
values = np.random.rand(10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [75]:
bins = [0,0.2,0.4,0.6,0.8,1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

**7.3 문자열 다루기**

In [76]:
val = 'a,b, guido'
val.split(',')

['a', 'b', ' guido']

In [77]:
pieces = [x.strip() for x in val.split(',')]      #strip: 좌,우 공백문자 없애기
pieces

['a', 'b', 'guido']

In [78]:
first, second, third = pieces
first+'::'+second+'::'+third

'a::b::guido'

In [79]:
'::'.join(pieces)

'a::b::guido'

In [80]:
'guido' in val

True

In [81]:
val.index(',')      #찾지 못하면 예외를 발생시킴.

1

In [82]:
val.find(':')       #찾지 못하면 -1을 반환함. (예외 발생 X)

-1

In [83]:
val.count(',')

2

In [84]:
val.replace(',','::')

'a::b:: guido'

In [85]:
val.replace(',','')     #찾아낸 패턴을 다른 문자로 치환함.
                        #비어있는 문자열로 문자열을 대체하여, 패턴을 삭제하는 방법으로 자주 사용됨.

'ab guido'

**7.3.2 정규 표현식**

(점프 투 파이썬 WikiDocs를 활용한 개별 chapter 구성)

**7.3.3 pandas의 벡터화된 문자열 함수**