**5.2 핵심 기능**

**5.2.1 재색인**

In [1]:
import numpy as np
import pandas as pd

In [2]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [3]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [4]:
obj3 = pd.Series(['blue','purple','yellow'],index=[0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [5]:
obj3.reindex(range(6), method='ffill')      #method='ffill': reindex하며 누락된 값을 직전의 값으로 채워 넣는다.
obj3.reindex(range(6), method='bfill')      #method='bfill': reindex하며 누락된 값을 다음의 값으로 채워 넣는다.

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [6]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),
                     index=['a','c','d'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [7]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [8]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [9]:
#frame.loc[['a','b','c','d'], states]

**5.2.2 하나의 로우나 컬럼 삭제하기**

In [10]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [11]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [12]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [13]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio','Colorado','Utah','New York'],
                    columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [14]:
data.drop(['Colorado','Ohio'])      #axis=0 or axis='rows'가 생략된 것이다.

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [15]:
data.drop(['two'],axis=1)           #axis='columns'로도 표현 가능하다.

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [16]:
data.drop(['two','four'],axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

drop함수처럼 Series나 DataFrame의 크기 또는 형태를 변경하는 함수는 새로운 객체를 반환하는 대신 원본 객체를 변경한다.

In [17]:
obj.drop('c',inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

inplace옵션을 사용하는 경우 버려지는 값을 모두 삭제하므로 주의해서 사용해야한다.

**5.2.3 색인하기, 선택하기, 거르기**

Series의 색인은 Numpy배열의 색인과 유사하게 동작하지만 정수가 아니어도 된다는 점이 다르다.

In [18]:
obj = pd.Series(np.arange(4.), index=['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [19]:
obj['b']

1.0

In [20]:
obj[1]

1.0

In [21]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [22]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [23]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [24]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [25]:
obj['b':'c']    #끝점을 포함한다는 것이 다른 슬라이싱과 다른 점!

b    1.0
c    2.0
dtype: float64

In [26]:
obj['b':'c']=5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [27]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index=['Ohio','Colorado','Utah','New York'],
                    columns=['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [28]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [29]:
data[['two','four']]

two  four
Ohio        1     3
Colorado    5     7
Utah        9    11
New York   13    15

In [30]:
data[:2]      #slicing으로 하면 로우를 선택함.

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [31]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [32]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [33]:
data[data<5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [34]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [35]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [36]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [37]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [38]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [39]:
data.iloc[:,:3][data.three>5]         #data.three = data['three']

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

**5.2.4 정수 색인**

In [40]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [41]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])
ser2[-1]

2.0

In [42]:
ser[:1]       #정숫값을 담고 있는 index가 있따면 우선적으로 라벨을 먼저 찾아본다.

0    0.0
dtype: float64

In [43]:
ser.loc[:1]   #라벨로 indexing을 하므로 끝값도 포함된다.

0    0.0
1    1.0
dtype: float64

In [44]:
ser.iloc[:1]  #정수로 indexing을 하므로 끝값은 포함되지 않는다.

0    0.0
dtype: float64

**5.2.5 산술 연산과 데이터 정렬**

다른 index를 가지고 있는 객체 간의 산술연산이 가능하다.

In [48]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a','c','d','e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a','c','e','f','g'])

In [49]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [50]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [51]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [53]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'),index=['Ohio','Texas','Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [54]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [55]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [57]:
df1+df2       #양쪽에 다 존재하지 않는 라벨에 대해서는 없는 값으로 나타난다.

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [58]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[3,4]})

In [59]:
df1

A
0  1
1  2

In [60]:
df2

B
0  3
1  4

In [62]:
df1-df2       #공통되는 부분만 원소별로 계산한다.

A   B
0 NaN NaN
1 NaN NaN

**산술 연산 메서드에 채워 넣을 값 지정하기**

In [64]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape(4,5), columns=list('abcde'))
df2.loc[1,'b'] = np.nan

In [65]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [66]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [67]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [74]:
df1.add(df2,fill_value=0)        #fill_value=0의 의미: 겹치지 않는 부분은 0으로 하여 덧셈을 한다.

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [75]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [97]:
df1.rdiv(5)       #5/df1

a         b         c         d
0    inf  5.000000  2.500000  1.666667
1  1.250  1.000000  0.833333  0.714286
2  0.625  0.555556  0.500000  0.454545

In [98]:
df1.div(5)        #df1/5

a    b    c    d
0  0.0  0.2  0.4  0.6
1  0.8  1.0  1.2  1.4
2  1.6  1.8  2.0  2.2

In [83]:
df1.reindex(columns=df2.columns)

a    b     c     d   e
0  0.0  1.0   2.0   3.0 NaN
1  4.0  5.0   6.0   7.0 NaN
2  8.0  9.0  10.0  11.0 NaN

In [90]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

**DataFrame과 Series 간의 연산**

In [99]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [100]:
arr[0]

array([0., 1., 2., 3.])

In [101]:
arr-arr[0]        #arr에서 arr[0]을 빼면 각 로우에 대해 한 번씩 수행된다.   #브로드캐시팅이라고 함.

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [102]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), index=['Utah','Ohio','Texas','Oregon'])
series = frame.iloc[0]

In [103]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [104]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [105]:
frame - series            #column 연산

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [107]:
series2 = pd.Series(range(3), index=['b','e','f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [108]:
series3 = frame['d']

In [109]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [110]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [115]:
frame.sub(series3, axis=0)      #row 연산

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0